# Generated by Django 4.0.4 on 2022-05-13 11:41

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0002_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
